apiVersion: v1
kind: Pod
metadata:
  name: apache2app
  labels:
      app: apache2app
spec:
    containers:
        - name: apache2cont
          image: addu0411/adnan:adn
          resources:
              requests:
                  cpu: "500m"
                  memory: "400Mi" 
          ports:
              - protocol: TCP
                containerPort: 8080
                name: http

                




