apiVersion: v1
kind: Pod
metadata:
        name: nginxapp
        #  label:
        #     app: nginxapp
spec:
    containers:
        - name: nginxcont
          image: addu0411/adnan:adn
          resources:
              requests:
                  cpu: "10m"
                  memory: "12Mi" 
          ports:
              - protocol: TCP
                containerPort: 80
                name: http

                apiVersion: v1
kind:  Service
metadata:
      name: loadbalancer
spec:
    selector:
        app:  nginxapp3
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 80
        name: http