apiVersion: v1
kind: Pod
metadata:
  name: nginxapp
  labels:
      app: nginxapp
spec:
    containers:
        - name: nginxcont
          image: addu0411/adnan:adn
          resources:
              requests:
                  cpu: "500m"
                  memory: "400Mi" 
          ports:
              - protocol: TCP
                containerPort: 80
                name: http

                




