apiVersion: v1
kind:  Service
metadata:
        name: loadbalancer
spec:
      selector:
          app:  nginxapp
        type: LoadBalancer
        ports:
        - port: 80
          targetPort: 80
          name: http